### ISSUE TITLE
Navigation Overhaul

### ISSUE THREAD

**Issue by RitaOak** [oaeproject/Biscuit-ux#55]
Current version of the main sidebar navigation (left) needs updating, as it should contain the following buttons:

1. New File
2. Create
3. Notifications

It's better to keep these options contained and easily accessible in one place, instead of scattered across the interface.

**Comment by ROak93** [comment]
The design for this change has been created. 

<img src="https://user-images.githubusercontent.com/9168624/95093366-9aa84900-0720-11eb-8d06-ee2637f2be1b.png" data-canonical-src="https://user-images.githubusercontent.com/9168624/95093366-9aa84900-0720-11eb-8d06-ee2637f2be1b.png" width="200" height="400" />

**Comment by ROak93** [comment]
The biggest changes in this new version are the following:

1. The sidebar will be white (#FFFF), in order to contrast with the content background (#F6F7F7);
2. Avatar and avatar dropdown (which contains the logout button) changes location to the bottom of the sidebar;
3. While notifications are now available in their own dedicated page, the latest 5 notifications are displayed under the main menu navigation buttons;
4. Included buttons: New File + Create + Notifications, and created a better hierarchy for the navigation.

Will be implemented soon.

**Comment by ROak93** [comment]
Implemented.

Removed /Latest Notifications/ as right now we will still be using the default notifications system
